### ISSUE TITLE
There should a logging mechanism to provide from terminal.

### ISSUE THREAD

**Issue by PranavBhattrai** [therealahrion/Audio-Compatibility-Patch#2]
As a way to provide feedback and to know whether this module is working or not!

Logging is best mechanism we provide through terminal. It's a trending feature this days in modules.

**Comment by Zackptg5** [comment]
This mod has been taken over by JohnFawkes. New repo is here: https://github.com/JohnFawkes/Audio-Compatibility-Patch

There's no need for a logging mechanism with this mod, it's not an app or anything. If you want to see audio routing changes after applying this log, just check the logcat.

We also don't need to in this case because we know exactly what each change already does - it's not like a lot of other audio mods that have janky apps or lib replacements with unpredictable behavior. The changes themselves and the results of which are well documented both in the xda support thread if you search it, and in android source itself: https://android.googlesource.com/platform/system/core/+/abcb99927d9ad3f66288a5ce16d7c86c14b49249/include/system/audio.h
